equilibreapp/cadastro/urls.py
from django.urls import path
from . import views

app_name = 'cadastro'

urlpatterns = [
    path('', views.home, name='home'),
]

equilibreapp/urls.py
from django.contrib import admin
from django.urls import path, include
from equilibreapp.views import home
from .views import home as equilibre_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', equilibre_home, name='home'),
    path('cadastro/', include('equilibreapp.cadastro.urls'))
]

equilibreapp/cadastro/models.py
from django.db import models

# Create your models here.

equilibreapp/cadastro/views.py
# equilibreapp/cadastro/views.py

from django.shortcuts import render

def home(request):
    return render(request,'cadastro/home.html')

equilibreapp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

equilibreapp/cadastro/templates/cadastro/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Cadastro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 offiset-md-3">
                <h1 class="mt-5">Lista de Cadastro</h1>

            <form action="{% url 'cadastro:home' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Escreva Sua Tarefa" aria-label="Escreva Sua Tarefa" aria-describedby="button-addon2" name="nome">
                <button type="submit" class="btn btn-primary" id="button-addon2">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>